USE cocktails;

CREATE TABLE Library (
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Name NVARCHAR(255)
);

CREATE TABLE Recipe (
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	LibraryId UNIQUEIDENTIFIER NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	Instructions NVARCHAR(max),
	Source NVARCHAR(max),
	CONSTRAINT FK_LibraryRecipe FOREIGN KEY(LibraryId) REFERENCES Library(Id)
);

CREATE TABLE ComponentType (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Type NVARCHAR(255) --CHANGE "TYPE" TO "NAME" AND RENAME IN CODE!
);

CREATE TABLE Component (
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	ComponentTypeId INT NOT NULL,
	Name NVARCHAR(255),
	Description NVARCHAR(max),
	CONSTRAINT FK_ComponentTypeComponent FOREIGN KEY(ComponentTypeId) REFERENCES ComponentType(Id)
);

CREATE TABLE Unit (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) --NOT NULL
);

CREATE TABLE Ingredient (
	Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	RecipeId UNIQUEIDENTIFIER NOT NULL,
	ComponentId UNIQUEIDENTIFIER NOT NULL,
	Quantity NVARCHAR(255),
	UnitId INT,
	Number INT,
	CONSTRAINT FK_RecipeIngredient FOREIGN KEY(RecipeId) REFERENCES  Recipe(Id),
	CONSTRAINT FK_ComponentIngredient FOREIGN KEY(ComponentId) REFERENCES Component(Id),
	CONSTRAINT FK_UnitIngredient FOREIGN KEY(UnitId) REFERENCES Unit(Id)
);
