USE cocktails;

ALTER TABLE Recipe
DROP CONSTRAINT IF EXISTS FK_LibraryRecipe;
ALTER TABLE Recipe
DROP CONSTRAINT IF EXISTS FK_MixTypeRecipe;

ALTER TABLE Component
DROP CONSTRAINT IF EXISTS FK_ComponentTypeComponent;

ALTER TABLE Ingredient
DROP CONSTRAINT IF EXISTS FK_RecipeIngredient;
ALTER TABLE Ingredient
DROP CONSTRAINT IF EXISTS FK_ComponentIngredient;
ALTER TABLE Ingredient
DROP CONSTRAINT IF EXISTS FK_UnitIngredient;

DROP TABLE IF EXISTS Recipe;

DROP TABLE IF EXISTS MixType;

DROP TABLE IF EXISTS Ingredient;

DROP TABLE IF EXISTS Component;

DROP TABLE IF EXISTS ComponentType;

DROP TABLE IF EXISTS Unit;

DROP TABLE IF EXISTS Library;
